default: &default
  adapter: postgresql
  pool: 5
  username: mingos
  password: 12345678

development:
  <<: *default
  database: plans_development

test:
  <<: *default
  database: plans_test

production:
  <<: *default
  database: plans_production

